#################################################
## Configuration file for PhyloProcessR
## Workflow X0: rapid per-sample read screening
## This workflow downloads or stages one sample at a time, cleans the reads,
## and estimates capture success while limiting temporary disk use.
#################################################

# Package version
#########################
# TRUE installs the latest GitHub development version before the run.
install.latest.github = FALSE

# Working directory
#########################
# *** Full paths should be used whenever possible
working.directory = "/Path/to/where/the/stuff/will/happen"

# Global settings
#########################
# Number of threads
threads = 16
# Amount of memory to allocate in GB
memory = 120
# Hide verbose output for each function
quiet = FALSE

# Read input settings
#########################
# TRUE  = download reads from Dropbox (requires dropbox settings below)
# FALSE = use a local directory of reads (set read.directory below)
use.dropbox = FALSE
# Path to a local directory of raw reads; used when use.dropbox = FALSE.
# Reads may be in per-sample sub-directories or flat with a shared filename prefix.
read.directory = "/Path/to/local/raw-reads"
# CSV with two columns: "File" (filename prefix) and "Sample" (desired sample name).
# Used for Dropbox download sample matching; set to NULL if use.dropbox = FALSE.
sample.file = "file_rename.csv"
# Expected read length in bp, used for MegaBasePairs calculation
read.length = 150
# Name of the folder for all processed reads (created in working.directory)
processed.reads = "processed-reads"

# Dropbox download settings (only needed when use.dropbox = TRUE)
#########################
# Token file previously generated by the rdrop2 package (see rdrop2 documentation)
dropbox.token = "/Path/to/dropbox-token.RDS"
# The Dropbox directory containing all sample read folders
dropbox.directory = "/Research/3_Sequence-Database/Raw-Reads"

# Cleanup settings
#########################
# TRUE = delete raw downloaded reads after processing each sample (recommended for large datasets)
delete.raw.reads = TRUE
# TRUE = delete cleaned reads after capture assessment (recommended for large datasets)
delete.cleaned.reads = TRUE

# Capture assessment settings
#########################
# Full path to the target probe/marker FASTA used for sequence capture
target.fasta = "/Path/to/probe-set.fa"

# Read-cleaning settings
#########################
# These values match the current fastpClean interface in PhyloProcessR.
fastp.remove.adaptors = TRUE
fastp.remove.duplicate.reads = TRUE
fastp.error.correction = TRUE
fastp.quality.trim.reads = FALSE
fastp.quality.filter = TRUE
fastp.low.complexity.filter = TRUE
fastp.trim.poly.x = TRUE
fastp.min.read.length = 60

# Barcode scan settings
#########################
# TRUE runs MItoTrawlR::barcodeSampleScan after read cleaning.
# FALSE = skip barcode identification entirely
run.barcode.scan = FALSE
# Full path to a FASTA of barcode reference sequence(s) used to recruit reads
# (e.g. a 16S rRNA or COI representative for the target taxa)
barcode.fasta = "/Path/to/barcode-reference.fa"
# Full path to a FASTA of named barcode sequences for local BLAST identification.
# NULL (recommended) queries NCBI nt remotely — no local database needed,
# but requires an internet connection. Remote queries are slower; for large
# datasets set this to a curated local database to avoid NCBI rate limits.
barcode.database.fasta = NULL
# Number of BLAST hits retained for each sample.
barcode.hits.per.sample = 5
# Minimum number of iterative assembly rounds before convergence is tested.
barcode.min.iterations = 3
# Maximum number of iterative assembly rounds.
barcode.max.iterations = 10
# Starting BBMap minimum identity for read recruitment.
barcode.min.ref.id = 0.70
# Fraction above reference length that triggers the maximum-length guard.
barcode.per.max.length = 0.50

# Program paths
#########################
# When installed via conda, only the path to the conda bin directory is needed
conda.env = "/Path/to/conda/env/bin"
fastp.path = conda.env
samtools.path = conda.env
bwa.path = conda.env
bbmap.path = conda.env
spades.path = conda.env
cap3.path = conda.env
blast.path = conda.env
